module.exports = {
 pixelHeight : 111.95,

roster : {
"A.I.M. Infector":             0,
"A.I.M. Monstrosity":          1,
"A.I.M. Assaulter":          2,
"A.I.M. Researcher":          3,
"A.I.M. Security":          4,
"Ant-Man":          5,
"Mordo":          6,
"Black Panther":          7,
"Black Widow":          8,
"Bullseye":          9,
"Cable":          10,
"Captain America":          11,
"Captain Marvel":          12,
"Carnage":          13,
"Civilian1":          14,
"Civilian2":          15,
"Crossbones":          16,
"Daredevil":          17,
"Deadpool":          18,
"Doctor Strange":          19,
"Drax":          20,
"Elektra":          21,
"Falcon":          22,
"Gamora":          23,
"Groot":          24,
"Hand Assassin":          25,
"Hand Blademaster":          26,
"Hand Sorceress":          27,
"Hand Archer":          28,
"Hand Sentry":          29,
"Hawkeye":          30,
"Hulk":          31,
"Hydra Grenadier":          32,
"Hydra Rifle Trooper":          33,
"Hydra Sniper":          34,
"Hydra Scientist":          35,
"Hydra Armored Guard":          36,
"Iron Fist":          37,
"Iron Man":          38,
"Juggernaut":          39,
"Jessica Jones":          40,
"Killmonger":          41,
"Kingpin":          42,
"Kree Cyborg":          43,
"Korath":          44,
"Kree Noble":          45,
"Kree Cyborg(Dupe)":     46,
"Kree Reaper":          47,
"Kree Oracle":          48,
"Kree Royal Guard":          49,
"Loki":          50,
"Luke Cage":          51,
"M'Baku":          52,
"Magneto":          53,
"Mantis":          54,
"Mercenary Soldier":          55,
"Mercenary Sniper":          56,
"Mercenary Lieutenant":          57,
"Mercenary Riot Guard":          58,
"Mercenary Body Guard":          59,
"Minn-Erva":          60,
"Ms Marvel":          61,
"Mystique":          62,
"Nebula":          63,
"Nick Fury":          64,
"Punisher":          65,
"Night Nurse":          66,
"Nobu":          67,
"Okoye":          68,
"Punisher(Dupe)":69,
"Pyro":          70,
"Quake":          71,
"Ravager Boomer":          72,
"Ravager Stitcher":          73,
"Ravager Bruiser":          74,
"Red Skull":          75,
"Scarlet Witch":          76,
"Rescue":          77,
"Rocket Raccoon":          78,
"Ronan":          79,
"Sabretooth":          80,
"Scarlet Witch(Dupe)": 81,
"Scientist Supreme":          82,
"S.H.I.E.L.D. Assault":          83,
"S.H.I.E.L.D. Trooper":          84,
"S.H.I.E.L.D. Trooper(Dupe)": 85,
"S.H.I.E.L.D. Medic":          86,
"S.H.I.E.L.D. Operative":          87,
"S.H.I.E.L.D. Security":          88,
"Shuri":          89,
"Spider-Man":          90,
"Star-Lord":          91,
"Storm":          92,
"Thanos":          93,
"Thor":          94,
"Green Goblin":          95,
"Spider-man [Miles]": 96,
"Ultimus":          97,
"Ultron":          98,
"Ultron Fortifier":          99,
"Ultron Incinerator":          100,
"Ultron Accelerator":          101,
"Ultron(Dupe)":                102,
"Ultron Fabricator":          103,
"Ultron Reinforcer":          104,
"Civilian3":          105,
"Venom":          106,
"Vision":          107,
"War Machine":          108,
"Wasp":          109,
"Winter Soldier":          110,
"Wolverine":          111,
"Yellowjacket":          112,
"Yondu":          113
},

//TODO: set this to get the actual character position
getBGPosition: function(char){
  return 1.754386;//(this.roster[char] * this.pixelHeight)/127.65;
}
}
