module.exports = {

pixelHeight: 110,

roster : {
"A.I.M. Infector":             0,
"A.I.M. Monstrosity":          1,
"A.I.M. Assaulter":          2,
"A.I.M. Researcher":          3,
"A.I.M. Security":          4,
"America Chavez":   5,
"Ant-Man":          6,
"Mordo":          7,
"Black Panther":          8,
"Black Widow":          9,
"Bullseye":          10,
"Cable":          11,
"Captain America":          12,
"Captain Marvel":          13,
"Carnage":          14,
"Colossus":         15,
"Crossbones":          16,
"Cyclops":          17,
"Daredevil":          18,
"Phoenix":          19,
"Deadpool":          20,
"Doctor Strange":          21,
"Drax":          22,
"Elektra":          23,
"Falcon":          24,
"Gamora":          25,
"Groot":          26,
"Hand Assassin":          27,
"Hand Blademaster":          28,
"Hand Archer":          29,
"Hand Sorceress":          30,
"Hand Sentry":          31,
"Hawkeye":          32,
"Hulk":          33,
"Hydra Grenadier":          34,
"Hydra Rifle Trooper":          35,
"Hydra Sniper":          36,
"Hydra Scientist":          37,
"Hydra Armored Guard":          38,
"Iron Fist":          39,
"Iron Man":          40,
"Jessica Jones":          41,
"Juggernaut":          42,
"Killmonger":          43,
"Kingpin":          44,
"Korath":          45,
"Kree Noble":          46,
"Kree Cyborg":          47,
"Kree Reaper":          48,
"Kree Oracle":          49,
"Kree Royal Guard":          50,
"Loki":          51,
"Luke Cage":          52,
"M'Baku":          53,
"Magneto":          54,
"Mantis":          55,
"Mercenary Soldier":          56,
"Mercenary Sniper":          57,
"Mercenary Lieutenant":          58,
"Mercenary Riot Guard":          59,
"Minn-Erva":          60,
"Ms Marvel":          61,
"Mystique":          62,
"Nebula":          63,
"Nick Fury":          64,
"Night Nurse":          65,
"Nobu":          66,
"Okoye":          67,
"Phoenix": 68,
"Psylocke": 69,
"Pyro":          70,
"Quake":          71,
"Ravager Boomer":          72,
"Ravager Stitcher":          73,
"Ravager Bruiser":          74,
"Red Skull":          75,
"Rescue":          76,
"Rescue":          77,
"Rocket Raccoon":          78,
"Ronan":          79,
"Sabretooth":          80,
"Scarlet Witch": 81,
"Scientist Supreme":          82,
"S.H.I.E.L.D. Assault":          83,
"S.H.I.E.L.D. Trooper":          84,
"S.H.I.E.L.D. Medic":          85,
"S.H.I.E.L.D. Operative":          86,
"S.H.I.E.L.D. Security":          87,
"Shuri":          88,
"Spider-Man":          89,
"Star-Lord":          90,
"Storm":          91,
"Thanos":          92,
"Thor":          93,
"Green Goblin":          94,
"Spider-man [Miles]": 95,
"Ultimus":          96,
"Ultron":          97,
"Venom":          98,
"Vision":          99,
"War Machine":          100,
"Wasp":          101,
"Winter Soldier":          102,
"Wolverine":          103,
"Yondu":          104
},

//TODO: set this to get the actual character position
getBGPosition: function(char){
  return this.roster[char] * this.pixelHeight;
}
}
