module.exports = {

pixelHeight: 110,

roster : {
"A.I.M. Infector":             0,
"A.I.M. Monstrosity":          1,
"A.I.M. Assaulter":          2,
"A.I.M. Researcher":          3,
"A.I.M. Security":          4,
"America Chavez":   5,
"Ant-Man":          6,
"Mordo":          7,
"Black Panther":          8,
"Black Widow":          9,
"Bullseye":          10,
"Cable":          11,
"Captain America":          12,
"Captain Marvel":          13,
"Carnage":          14,
"Colossus":         15,
"Coulson":         16,
"Crossbones":          17,
"Cyclops":          18,
"Daredevil":          19,
"Phoenix":          20,
"Deadpool":          21,
"Doctor Strange":          22,
"Drax":          23,
"Elektra":          24,
"Falcon":          25,
"Gamora":          26,
"Groot":          27,
"Hand Assassin":          28,
"Hand Blademaster":       29,
"Hand Archer":          30,
"Hand Sorceress":          31,
"Hand Sentry":          32,
"Hawkeye":          33,
"Hulk":          34,
"Hydra Grenadier":          35,
"Hydra Rifle Trooper":       36,
"Hydra Sniper":          37,
"Hydra Scientist":       38,
"Hydra Armored Guard":   39,
"Iron Fist":          40,
"Iron Man":          41,
"Jessica Jones":       42,
"Juggernaut":          43,
"Killmonger":          44,
"Kingpin":          45,
"Korath":          46,
"Kree Noble":          47,
"Kree Cyborg":          48,
"Kree Reaper":          49,
"Kree Oracle":          50,
"Kree Royal Guard":     51,
"Loki":          52,
"Luke Cage":          53,
"M'Baku":          54,
"Magneto":          55,
"Mantis":          56,
"Mercenary Soldier":          57,
"Mercenary Sniper":          58,
"Mercenary Lieutenant":      59,
"Mercenary Riot Guard":      60,
"Minn-Erva":          61,
"Ms Marvel":          62,
"Mystique":          63,
"Nebula":          64,
"Nick Fury":          65,
"Night Nurse":        66,
"Nobu":          67,
"Okoye":          68,
"Dark Phoenix": 69,
"Psylocke": 70,
"Punisher": 71,
"Pyro":          72,
"Quake":          73,
"Ravager Boomer":          74,
"Ravager Stitcher":          75,
"Ravager Bruiser":          76,
"Red Skull":          77,
"Rescue":          78,
"Rocket Raccoon":          79,
"Ronan":          80,
"Sabretooth":          81,
"Scarlet Witch": 82,
"Scientist Supreme":          83,
"S.H.I.E.L.D. Assault":          84,
"S.H.I.E.L.D. Trooper":          85,
"S.H.I.E.L.D. Medic":          86,
"S.H.I.E.L.D. Operative":        87,
"S.H.I.E.L.D. Security":         88,
"Shuri":          89,
"Spider-Man":          90,
"Star-Lord":           91,
"Storm":          92,
"Thanos":          93,
"Thor":          94,
"Green Goblin":          95,
"Spider-man [Miles]": 96,
"Ultimus":          97,
"Ultron":          98,
"Venom":          99,
"Vision":          100,
"War Machine":          101,
"Wasp":          102,
"Winter Soldier":          103,
"Wolverine":          104,
"Yondu":          105
},

getBGPosition: function(char){
  return this.roster[""+char+""] * this.pixelHeight;
}
}
